name: CI
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - develop
jobs:
  test:
    name: Test All Application
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Preparing auto Integration"